window.GameAPI=(()=>{
 const key="no-rule-classroom-demo";
 const read=()=>JSON.parse(localStorage.getItem(key)||'{"students":{},"settings":{},"rules":{}}');
 const write=x=>localStorage.setItem(key,JSON.stringify(x));
 const uuid=()=>globalThis.crypto?.randomUUID?.()||`nrc-${Date.now()}-${Math.random().toString(16).slice(2)}`;
 const yes=(values,item)=>Array.isArray(values)&&values.includes(item)?1:0;
 const value=(data,field)=>data[field]??'';
 const snapshot=data=>{
  const reasons=data.phone_reason||[],fragments=data.final_boss_final_fragments||[],scores=data.final_profile_scores||{},top=data.ending_top3||[],scanner=data.level3_scanner_answers||[],r1=data.final_boss_round1_hits||[],r2=data.final_boss_round2_hits||[],r4a=data.final_boss_round4a_hits||[],r4b=data.final_boss_round4b_hits||[],core=data.final_boss_final_core_hits||[],status=data.class_state||{};
  return {student_id:value(data,'student_id'),class:value(data,'class'),seat:value(data,'seat'),avatar_id:value(data,'avatar_id'),prologue_answer:value(data,'prologue_answer'),level1_cleared:!!data.level1_cleared,phone_initial:value(data,'phone_initial'),phone_reason_avoid_self_distraction:yes(reasons,'避免自己分心'),phone_reason_avoid_affecting_others:yes(reasons,'避免影響其他同學'),phone_reason_maintain_learning_order:yes(reasons,'維持共同學習秩序'),phone_reason_reduce_teacher_management:yes(reasons,'降低老師一直提醒與管理的時間'),phone_reason_students_cannot_self_manage:yes(reasons,'學生完全無法自我管理'),phone_reason_no_rules_needed:yes(reasons,'根本不需要規範'),phone_event_answer:value(data,'phone_event_answer'),phone_after_event:value(data,'phone_after_event'),phone_changed:!!data.phone_changed,
   level2_cleared:!!data.level2_cleared,lunch_initial:value(data,'lunch_initial'),lunch_branch_answer:value(data,'lunch_branch_answer'),lunch_quiet_meaning:value(data,'lunch_quiet_meaning'),lunch_impact_definition:value(data,'lunch_impact_definition'),lunch_limit_reasonable:value(data,'lunch_limit_reasonable'),lunch_clarity:value(data,'lunch_clarity'),lunch_exception_answer:value(data,'lunch_exception_answer'),lunch_after_event:value(data,'lunch_after_event'),lunch_changed:!!data.lunch_changed,
   level3_cleared:!!data.level3_cleared,seat_vote_real:value(data,'seat_vote_real'),seat_preference:value(data,'seat_preference'),seat_selected_position:value(data,'seat_selected_position'),seat_selected_type:value(data,'seat_selected_type'),seat_preference_met:data.seat_preference_met??'',seat_response:value(data,'seat_response'),level3_scanner_q1:value(scanner,0),level3_scanner_q2:value(scanner,1),level3_scanner_q3:value(scanner,2),level3_scanner_q4:value(scanner,3),seat_rule_match:data.seat_rule_match??'',majority_rule_answer:value(data,'majority_rule_answer'),seat_final_answer:value(data,'seat_final_answer'),
   level4_cleared:!!data.level4_cleared,paper_cup_action:value(data,'paper_cup_action'),responsibility_question:value(data,'responsibility_question'),recycle_action:value(data,'recycle_action'),reminder_style:value(data,'reminder_style'),power_action:value(data,'power_action'),unassigned_task_answer:value(data,'unassigned_task_answer'),responsibility_final_answer:value(data,'responsibility_final_answer'),
   final_boss_cleared:!!data.final_boss_cleared,final_boss_round1_exec:yes(r1,'exec'),final_boss_round1_clear:yes(r1,'clear'),final_boss_round1_fair:yes(r1,'fair'),final_boss_round1_except:yes(r1,'except'),final_boss_round1_community:yes(r1,'community'),final_boss_scan_purpose:value(data,'final_boss_scan_purpose'),final_boss_scan_method:value(data,'final_boss_scan_method'),final_boss_round2_exec:yes(r2,'exec'),final_boss_round2_clear:yes(r2,'clear'),final_boss_round2_fair:yes(r2,'fair'),final_boss_round2_except:yes(r2,'except'),final_boss_round2_community:yes(r2,'community'),final_boss_round3_answer:value(data,'final_boss_round3_answer'),final_boss_round4a_exec:yes(r4a,'exec'),final_boss_round4a_clear:yes(r4a,'clear'),final_boss_round4a_fair:yes(r4a,'fair'),final_boss_round4a_except:yes(r4a,'except'),final_boss_round4a_community:yes(r4a,'community'),final_boss_round4b_exec:yes(r4b,'exec'),final_boss_round4b_clear:yes(r4b,'clear'),final_boss_round4b_fair:yes(r4b,'fair'),final_boss_round4b_except:yes(r4b,'except'),final_boss_round4b_community:yes(r4b,'community'),
   final_rule_fragment_individual_needs:yes(fragments,'👥 個別需求'),final_rule_fragment_actual_impact:yes(fragments,'👀 實際影響'),final_rule_fragment_rule_purpose:yes(fragments,'🎯 規則目的'),final_rule_fragment_reasonable_exception:yes(fragments,'🧩 合理例外'),final_rule_fragment_majority_support:yes(fragments,'🗳️ 多數支持'),final_rule_fragment_same_rule_for_all:yes(fragments,'📜 人人相同'),final_rule_fragment_execution_cost:yes(fragments,'🔧 執行成本'),final_rule_core_1:value(core,0),final_rule_core_2:value(core,1),final_rule_last:value(data,'final_boss_final_last'),
   ending_type:value(data,'ending_type'),ending_top1:value(top,0),ending_top2:value(top,1),ending_top3:value(top,2),profile_freedom:scores.freedom??'',profile_learning:scores.learning??'',profile_order:scores.order??'',profile_empathy:scores.empathy??'',profile_community:scores.community??'',profile_executability:scores.executability??'',status_freedom:status.freedom??50,status_learning:status.learning??50,status_order:status.order??50,status_empathy:status.empathy??50,status_community:status.community??50,started_at:value(data,'started_at'),updated_at:value(data,'updated_at')};
 };
 const syncStudent=record=>{
  const url=window.APP_CONFIG?.SHEET_SYNC_URL;
  if(!url||!record?.student_id)return Promise.resolve({skipped:true});
  const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),5000);
  return fetch(url,{method:'POST',body:JSON.stringify({action:'syncStudent',payload:{student_id:record.student_id,data:snapshot(record)}}),signal:controller.signal}).then(r=>r.ok?r.json():Promise.reject(new Error(`Sheet sync failed: ${r.status}`))).catch(error=>{console.warn('[Sheet sync] non-blocking failure',error);return {ok:false,error:String(error)}}).finally(()=>clearTimeout(timeout));
 };
 const call=async(action,payload={},token="")=>{
  const db=read(),cls=payload.class||"";db.settings[cls]||={class:cls,results_visible:false,formal_rules_visible:false,projection_slide:1};db.rules[cls]||={class:cls};
  const id=`${cls}-${payload.seat}`,students=Object.values(db.students).filter(x=>x.class===cls);
  if(action==='getStudent')return db.students[id]||null;
  if(action==='student'){db.students[id]={...(db.students[id]||{class:cls,seat:payload.seat,student_id:uuid(),started_at:new Date().toISOString()}),...payload.data,updated_at:new Date().toISOString()};if(!db.students[id].student_id)db.students[id].student_id=uuid();write(db);let checkpoint=payload.data?.avatar_id||payload.data?.ending_type||Object.keys(payload.data||{}).some(k=>k.endsWith('_cleared')&&payload.data[k]);if(checkpoint)void syncStudent(db.students[id]);return db.students[id]}
  if(action==='stats')return {students,settings:db.settings[cls],rules:db.rules[cls]};
  if(action==='settings'){db.settings[cls]={...db.settings[cls],...payload.data};write(db);return db.settings[cls]}
  if(action==='rules'){db.rules[cls]={...db.rules[cls],...payload.data};write(db);return db.rules[cls]}
  if(action==='reset'){Object.keys(db.students).filter(k=>k.startsWith(cls+'-')).forEach(k=>delete db.students[k]);write(db);return {ok:true}}
  if(action==='verify')return {ok:!token||token.length>0};
 };return {call,syncStudent,snapshot};
})();
