window.ENDING={
 labels:{freedom:"🕊️ 個人自由",learning:"📚 學習效率",order:"⚖️ 班級秩序",empathy:"❤️ 同學感受",community:"🤝 共同責任",executability:"🔧 可執行性"},
 types:{freedom:["🕊️ 自由守護者","你重視個人的自主空間，也會注意規範是否限制超過實際需要。","自由不只是少一點規則，也需要考慮自己的選擇是否影響別人。"],learning:["📚 學習領航員","你重視學習環境、時間與效率。","有效率的制度，也需要考慮不同同學的需求與感受。"],order:["⚖️ 秩序守門人","你相信共同生活需要清楚、穩定的界線。","秩序很重要，但規則也需要合理，並保留必要的例外。"],empathy:["❤️ 共感協調師","你會留意不同人的需求，也重視彼此能不能接受共同規則。","照顧感受很重要，但共同規範有時也不可能讓所有人都完全滿意。"],community:["🤝 共好行動者","你認為班級是一個需要共同維護的環境。","共同責任不是什麼事情都要你負責，而是在需要的時候願意多看一步。"],executability:["🔧 制度工程師","你不只看規則的目的，也會注意時間、人力、執行方式與長期可行性。","容易執行不代表一定合理，制度仍需要兼顧其他人的權益。"]},
 score(a){let s={freedom:0,learning:0,order:0,empathy:0,community:0,executability:0};const add=(k,n=1)=>s[k]+=n; const has=(f,t)=>String(a[f]||'').includes(t);if(has('phone_initial','全天')||has('phone_after_event','全天'))add('freedom',2);if(has('phone_initial','到校')||has('phone_after_event','到校'))add('executability',2);if(has('phone_reason','學習')||has('seat_standard','學習'))add('learning',2);if(has('lunch_initial','安靜')||has('final_lunch','避免交談'))add('order',2);if(has('community_trash','撿起')||has('final_environment','共同維護'))add('community',3);if(has('community_reminder_style','影響')||has('seat_standard','需求'))add('empathy',2);(a.final_values||[]).forEach(v=>{let k=Object.keys(this.labels).find(x=>this.labels[x]===v);if(k)add(k,4)});return s},
 result(a){const s=this.score(a),order=Object.keys(s).sort((x,y)=>s[y]-s[x]||x.localeCompare(y));return {scores:s,type:order[0],top:order.slice(0,3)}}
};

/* LEVEL 3 的傾向計分集中在此處；僅供結局分析，學生不會在關卡中看見。 */
(()=>{const base=ENDING.score;ENDING.score=function(a){let s=base.call(this,a),has=(f,t)=>String(a[f]||'').includes(t),seatEarns=!a.seat_selected_limited;if(has('seat_vote_real','支持'))s.freedom+=1;if(seatEarns&&['back_window','window','aisle'].includes(a.seat_selected_type))s.freedom+=1;if(seatEarns&&a.seat_selected_type==='front')s.learning+=1;if(seatEarns&&a.seat_selected_type==='back_friend')s.empathy+=1;if(has('seat_response','維持原座位'))s.order+=1;if(has('seat_response','直接調整座位'))s.learning+=1;if(has('seat_response','重新投票'))s.community+=1;if(has('seat_response','重新檢討'))s.executability+=1;if(has('seat_standard_answer','學習表現'))s.learning+=1;if(has('seat_standard_answer','沒有直接關係'))s.order+=1;if(has('seat_standard_answer','上課狀況'))s.executability+=1;if(has('seat_standard_answer','目的'))s.executability+=2;if(has('majority_rule_answer','不一定'))s.executability+=1;if(has('seat_final_answer','不一定'))s.executability+=1;return s}})();

/* LEVEL 4｜最終結局的隱藏傾向，不影響關卡中的 CLASS STATUS。 */
(()=>{const base=ENDING.score;ENDING.score=function(a){let s=base.call(this,a),has=(f,t)=>String(a[f]||'').includes(t);if(has('paper_cup_action','順手撿起'))s.community+=2;if(has('paper_cup_action','找出是誰'))s.order+=1;if(has('reminder_style','欸，這個')){s.community+=2;s.empathy+=2}if(has('reminder_style','不說話'))s.community+=1;if(has('unassigned_task_answer','看見的人'))s.community+=2;if(has('unassigned_task_answer','重新把'))s.order+=1;if(has('responsibility_final_answer','不一定'))s.community+=2;return s}})();
