/* FINAL BOSS｜獨立模組；沿用既有 GameAPI、Hub、Avatar 與 CLASS STATUS。 */
(()=>{const KEY='nrc-final-boss-history',SK=[['exec','🔧','可執行性'],['clear','📏','明確性'],['fair','⚖️','規範合理性'],['except','🧩','合理例外'],['community','🤝','共同體責任']],N={freedom:'🕊️ 自由度',learning:'📚 學習效率',order:'⚖️ 班級秩序',empathy:'❤️ 同學滿意度',community:'🤝 共同責任'};let timer,review=null;
const E=x=>document.getElementById(x),ID=()=>JSON.parse(localStorage.getItem('nrc-id')||'null'),pos=p=>`${((p.avatar_index||0)%4)*33.333}% ${(p.avatar_index||0)>3?'100%':'0%'}`,state=p=>({freedom:50,learning:50,order:50,empathy:50,community:50,...(p.class_state||{})}),clearTimer=()=>{clearTimeout(timer);timer=null};
const history=p=>{let h=JSON.parse(sessionStorage.getItem(KEY)||'[]');h.push({phase:p.final_boss_phase||'intro',dialogue:p.final_boss_dialogue_index||0,caseIndex:p.final_boss_case_index||0});sessionStorage.setItem(KEY,JSON.stringify(h))};
const reviewForward=()=>{if(!review)return;let next=review.future.pop();if(!next||!review.future.length){review=null;return window.NRC_FINAL_BOSS()}review.view=next;window.NRC_FINAL_BOSS()};
const lockReview=p=>{if(!review)return;let panel=document.querySelector('.fb-layer');if(!panel||panel.querySelector('.fb-review-note'))return;let value=p._review_value,values=Array.isArray(value)?value:[value],norm=x=>String(x??'').replace(/<[^>]*>|[A-D]\.|[「」。]/g,'').replace(/\s+/g,'').trim();panel.querySelectorAll('button').forEach(b=>{b.disabled=true;b.setAttribute('aria-disabled','true');let candidate=b.dataset.s??b.dataset.v??b.textContent;if(values.some(v=>norm(candidate).includes(norm(v)))){b.classList.add('picked','review-selected');b.setAttribute('aria-current','true')}});panel.insertAdjacentHTML('beforeend',`<p class="l3-review-note fb-review-note">回看模式｜技能、答案與戰鬥結果已鎖定</p>${value!==undefined&&value!==null?`<p class="feedback review-answer">✓ 你當時的選擇：${Array.isArray(value)?value.join('、'):value}</p>`:''}<button class="primary fb-review-next">繼續往前閱讀</button>`);panel.querySelector('.fb-review-next').onclick=reviewForward};
const hud=p=>{let s=state(p),d=p.last_impact||{};return `<aside class="rpg-hud fb-hud"><b>🏫 CLASS STATUS</b>${Object.entries(N).map(([k,n])=>`<div class="meter"><span>${n}</span><strong>${s[k]}</strong><i style="width:${s[k]}%"></i>${d[k]?`<em>${d[k]>0?'▲':'▼'}${Math.abs(d[k])}</em>`:''}</div>`).join('')}</aside><div class="fb-player"><i class="avatar-sprite" style="background-position:${pos(p)}"></i><b>${p.avatar_id}</b></div>`};
const hp=p=>p.final_boss_hp??100,combo=p=>p.final_boss_combo||0,skillCards=()=>`<p class="fb-action-guide">找出這條規則最大的漏洞，選擇最適合的技能發動攻擊！</p><div class="fb-skill-cards">${SK.map(([id,icon,name])=>`<button class="fb-skill" data-s="${id}">${icon} ${name}<small>技能攻擊</small></button>`).join('')}</div>`;
const draw=(p,tag,heading,body,actions='',cls='')=>{clearTimer();let round=/^ROUND [1-4]｜/;E('stage-label').textContent='FINAL BOSS｜規則漏洞大決戰';E('app').innerHTML=`<section class="final-boss-scene ${cls}"><img class="scene-img" src="assets/final-boss-classroom.png" alt="進入規則漏洞王戰鬥狀態的教室">${hud(p)}<i class="fb-avatar" style="background-position:${pos(p)}"></i><img class="fb-boss" src="assets/rule-bug-king.png" alt="規則漏洞王"><div class="fb-paper">📜 班級規則<br>看起來完美？</div><div class="fb-particles"><i style="--i:0"></i><i style="--i:1"></i><i style="--i:2"></i><i style="--i:3"></i><i style="--i:4"></i></div><div class="fb-combo">⚡ COMBO ×${combo(p)}</div><div class="fb-hp">RULE BUG KING HP <b>${hp(p)}%</b><i style="width:${hp(p)}%"></i></div><section class="dialogue fb-layer"><p class="eyebrow ${round.test(tag)?'fb-round-label':''}">${tag}</p><h1 class="${round.test(heading)?'fb-round-label':''}">${heading}</h1>${body}${actions}</section></section>`};
const go=async(p,data,keep=true)=>{clearTimer();if(review)return reviewForward();if(keep)history(p);await GameAPI.call('student',{class:p.class,seat:p.seat,data:{flow:'finalboss',...data}});window.NRC_FINAL_BOSS()};
const apply=async(p,key,answer,delta,next,extra={})=>{if(p.final_boss_impacts?.[key])return go(p,{final_boss_phase:next,last_impact:{}});let s=state(p);Object.entries(delta).forEach(([k,v])=>s[k]=Math.max(0,Math.min(100,s[k]+v)));await go(p,{...extra,class_state:s,last_impact:delta,final_boss_impacts:{...(p.final_boss_impacts||{}),[key]:true},final_boss_phase:next})};
const impact=(p,next,copy,label='⚔️ 進入下一回合')=>{let s=state(p),d=p.last_impact||{};draw(p,'你的選擇造成的影響','CLASS STATUS',`<div class="impact-result">${Object.entries(d).map(([k,v])=>`<span>${N[k]} <b>${s[k]-v} → ${s[k]}</b> <strong class="${v>0?'up':'down'}">${v>0?'+':''}${v}</strong></span>`).join('')}</div><p>${copy}</p>`,`<div class="final-boss-next-action"><button class="primary" id="fb-next">${label}</button></div>`);E('fb-next').onclick=()=>go(p,{final_boss_phase:next,last_impact:{}})};
const roundComplete=(p,tag,title,body,next,label='⚔️ 進入下一回合')=>{draw(p,tag,title,body,`<div class="final-boss-next-action"><button class="primary" id="fb-round-next">${label}</button></div>`,'fb-hit');E('fb-round-next').onclick=()=>go(p,{final_boss_phase:next,final_boss_message:'',last_impact:{}})};
const endingMeta=(p)=>{let r=ENDING.result(p),type=r.type,info=ENDING.types[type],scores=r.scores,copy={freedom:['你在面對規則時，常常會注意：「真的有必要管這麼多嗎？」你重視個人的自主空間，也會注意規則是否限制超過實際需要。','自由不只是少一點規則，也需要考慮自己的選擇是否影響別人。'],learning:['你常常會想：「這樣能不能讓大家更順利學習？」你重視學習環境、時間與效率。','有效率的制度，也需要考慮不同同學的需求與感受。'],order:['你相信共同生活需要清楚、穩定的界線。當大家知道什麼可以做、什麼不能做，班級比較容易順利運作。','秩序很重要，但規則本身也需要合理。'],empathy:['你做決定時，經常會注意：「這個規定會讓別人有什麼感受？」你重視不同人的需求與接受程度。','照顧感受很重要，但共同規範也不可能讓每個人完全滿意。'],community:['你認為班級不是一群各自生活的人，而是一個需要共同維護的環境。除了完成自己的責任，你也願意注意整體的需要。','共同責任不是所有事情都由你負責，而是在需要的時候願意多看一步。'],executability:['你面對規則時，很容易注意：「這個制度真的做得到嗎？」你會注意時間、人力、執行方式與長期可行性。','容易執行不代表一定合理，制度仍需要兼顧其他人的需求與權益。']}[type]||[info[1],info[2]];return {type,title:info[0],description:copy[0],reminder:copy[1],scores,top:r.top.map(k=>({key:k,label:ENDING.labels[k],score:scores[k]}))}};
const persistEnding=async p=>{let e=endingMeta(p);if(p.final_boss_cleared&&p.ending_type&&Array.isArray(p.ending_top3)&&p.final_profile_scores)return e;await GameAPI.call('student',{class:p.class,seat:p.seat,data:{final_boss_cleared:true,ending_type:e.type,ending_top3:e.top.map(x=>x.key),final_profile_scores:e.scores,final_boss_phase:'ending-card',last_impact:{}}});return e};
const avatarHero=p=>`<div class="fb-ending-avatar"><i class="avatar-sprite" style="background-position:${pos(p)}"></i><b>${p.avatar_id||'班級新成員'}</b></div>`;
const radar=e=>`<section class="fb-radar"><h2>🔍 我的規範雷達</h2>${e.top.map((x,i)=>`<div><span>${x.label}</span><b>${'★'.repeat(Math.max(1,5-i))}${'☆'.repeat(i)}</b></div>`).join('')}<p>這不是能力高低，而是你在面對規則時，比較容易先注意到的角度。</p></section>`;
const attack=(p,needed,next,hitText,hpAfter,field)=>document.querySelectorAll('.fb-skill').forEach(b=>b.onclick=async()=>{let choice=b.dataset.s,first=!p[`${field}_wrong`];if(!needed.includes(choice)){await go(p,{[`${field}_wrong`]:true,final_boss_combo:0,final_boss_message:'👾「嘿嘿……這招好像沒打到問題核心。」'},false);return}let found=[...(p[field]||[]),choice];if(found.length===new Set(found).size){let add=first?1:0,complete=needed.every(x=>found.includes(x)),data={[field]:found,final_boss_combo:combo(p)+add,final_boss_hp:complete?hpAfter:Math.max(hp(p)-10,hpAfter),final_boss_message:complete?hitText:'💥 HIT！Boss 的護盾破了一層。再找一個漏洞。'};if(complete)data.final_boss_phase=next;await go(p,data,false)}});
const dialogue=(p,items,next)=>{let i=p.final_boss_dialogue_index||0,x=items[i],last=i===items.length-1;draw(p,'ROUND 1｜遲到者禁止進入教室','情境演出',`<div class="fb-dialogue"><i class="avatar-sprite" style="background-position:${pos({...p,avatar_index:x[0]})}"></i><div><b>${x[1]}</b>「${x[2]}」</div></div>`,`<button class="secondary" id="fb-next-dialogue">下一頁</button>`);E('fb-next-dialogue').onclick=()=>go(p,{final_boss_phase:last?next:'r1-dialogue',final_boss_dialogue_index:last?0:i+1})};
window.NRC_FINAL_BOSS=async()=>{let id=ID(),stored=id&&await GameAPI.call('getStudent',id),p=review?{...review.official,final_boss_phase:review.view.phase,final_boss_dialogue_index:review.view.dialogue||0,final_boss_case_index:review.view.caseIndex||0,last_impact:{}}:stored;if(!p)return;let q=p.final_boss_phase||'intro';if(review){if(q==='r1-attack'){p._review_value=p.final_boss_round1_hits||[];p.final_boss_round1_hits=[]}else if(q==='r2-scan'){p._review_value=[p.final_boss_scan_purpose,p.final_boss_scan_method].filter(Boolean);p.final_boss_scan_purpose='';p.final_boss_scan_method=''}else if(q==='r2-attack'){p._review_value=p.final_boss_round2_hits||[];p.final_boss_round2_hits=[]}else if(q==='r3'){p._review_value=p.final_boss_round3_answer;p.final_boss_impacts={...(p.final_boss_impacts||{})};delete p.final_boss_impacts.r3}else if(q==='r4'){p._review_value=p.final_boss_round4a_hits||[];p.final_boss_round4a_hits=[]}else if(q==='r4-patch'){p._review_value=p.final_boss_round4b_hits||[];p.final_boss_round4b_hits=[]}else if(q==='final-decision'){p._review_value=p.final_boss_final_core_hits||[];p.final_boss_final_fragments=[];p.final_boss_final_core_hits=[];p.final_boss_impacts={...(p.final_boss_impacts||{})};delete p.final_boss_impacts['final-decision']}requestAnimationFrame(()=>lockReview(p))}let msg=p.final_boss_message?`<div class="fb-message warn">${p.final_boss_message}</div>`:'';
if(q==='intro'){draw(p,'👾 FINAL BOSS','規則漏洞大決戰',`<p>你已走過手機、午休、座位、公共環境四個班級事件。</p><div class="fb-skill-cards">${SK.map(([,i,n])=>`<div class="fb-skill">${i} ${n}</div>`).join('')}</div><p class="fb-message">規則不是「有寫」，就一定是好規則。</p>`,`<button class="primary" id="fb-start">進入戰鬥</button>`);E('fb-start').onclick=()=>go(p,{final_boss_phase:'warning',final_boss_hp:100,final_boss_combo:0,last_impact:{}});return}
if(q==='warning'){draw(p,'⚠️ WARNING','RULE SYSTEM ERROR',`<div class="fb-message warn"><b>UNKNOWN ENTITY DETECTED</b><br>黑板文字閃動、規則紙飛入……</div>`,`<button class="primary" id="fb-boss">確認警報</button>`,'fb-warning');E('fb-boss').onclick=()=>go(p,{final_boss_phase:'boss-intro'});return}
if(q==='boss-intro'){draw(p,'👾 RULE BUG KING','規則漏洞王出現！',`<p>「你們不是很喜歡訂班規嗎？那我就送你們幾條——完美的班規！」</p><p class="fb-message">❓ 模糊　⚙️ 做不到　⚖️ 不合理　🔒 沒有例外　🙈 不關我的事</p>`,`<button class="primary" id="fb-r1">面對第一條規則</button>`);E('fb-r1').onclick=()=>go(p,{final_boss_phase:'r1-dialogue',final_boss_dialogue_index:0});return}
if(q==='r1-dialogue')return dialogue(p,[[0,'阿樂','我剛剛肚子痛去廁所……'],[1,'小晴','老師叫我去教務處拿東西。'],[2,'阿凱','我去合作社買東西排太久。'],[0,'規則漏洞王','三個人都遲到啊！同一條規則，大家都一樣！']],'r1-attack');
if(q==='r1-complete'||(q==='r1-attack'&&['fair','except'].every(x=>(p.final_boss_round1_hits||[]).includes(x))))return roundComplete({...p,final_boss_hp:80},'💥 雙重破解！','ROUND 1｜遲到者禁止進入教室',`<div class="fb-rule"><b>📜 班級規則</b>上課鐘響後才進入教室的人，一律不得進入教室，等到下課才能進入。</div><p class="fb-message">已找到：<b>2 / 2</b><br>你找到了這條規則的兩個主要問題：限制本身是否合理，以及是否需要合理例外，都需要進一步思考。</p><p><b>BOSS HP　100% → 80%</b></p>`,'r2-scan');
if(q==='r1-attack'){let got=p.final_boss_round1_hits||[];draw(p,'ROUND 1｜規則紙飛出','遲到者禁止進入教室',`<div class="fb-rule"><b>📜 班級規則</b>上課鐘響後才進入教室的人，一律不得進入教室，等到下課才能進入。</div><p>觀察這條規則的漏洞，選擇技能攻擊。${got.length?'已找到：'+got.length+' / 2':''}</p>${msg}`,skillCards(),'fb-hit');attack(p,['fair','except'],'r1-complete','💥 雙重破解！',80,'final_boss_round1_hits');return}
if(q==='r2-scan'){let purpose=p.final_boss_scan_purpose,method=p.final_boss_scan_method,opts=['提高作業準時繳交率','優先選擇座位','維持教室整潔','減少上課干擾','提高班級秩序'];draw(p,'ROUND 2｜🎯 TARGET SCAN','作業獎勵制度',`<div class="fb-rule"><b>📜 班級規則</b>每週作業全部準時繳交的同學，下次換座位時可以優先選擇座位。</div><p>先找出這條規則的目的與使用手段。</p><div class="fb-scan"><section><b>🎯 規則目的</b>${opts.slice().sort(()=>Math.random()-.5).map(x=>`<button data-t="purpose" data-v="${x}">${x}${purpose===x?'　✓':''}</button>`).join('')}</section><section><b>🎁 使用手段</b>${opts.slice().sort(()=>Math.random()-.5).map(x=>`<button data-t="method" data-v="${x}">${x}${method===x?'　✓':''}</button>`).join('')}</section></div>${msg}`,'','fb-target-scan');document.querySelectorAll('.fb-scan button').forEach(b=>b.onclick=async()=>{let d=b.dataset.t==='purpose'?{final_boss_scan_purpose:b.dataset.v}:{final_boss_scan_method:b.dataset.v};let n={...p,...d};if(n.final_boss_scan_purpose&&n.final_boss_scan_method){if(n.final_boss_scan_purpose==='提高作業準時繳交率'&&n.final_boss_scan_method==='優先選擇座位')return go(p,{...d,final_boss_phase:'r2-attack',final_boss_message:''});return go(p,{...d,final_boss_message:'系統：再看看這條規則真正想達成什麼。'},false)}go(p,d,false)});return}
if(q==='r2-complete'||(q==='r2-attack'&&(p.final_boss_round2_hits||[]).includes('fair')))return roundComplete({...p,final_boss_hp:65},'💥 PURPOSE–METHOD BREAK！','ROUND 2｜作業獎勵制度',`<p class="fb-message">規範合理性命中！<br>獎勵可能提高繳交意願，但仍要思考：「作業表現」是否適合決定「座位選擇權」？</p><p><b>BOSS HP　80% → 65%</b></p>`,'r3');
if(q==='r2-attack'){draw(p,'ROUND 2｜目的 × 手段','兩者有合理關係嗎？',`<p class="fb-message">提高作業準時繳交率　↓　？　↓　優先選擇座位</p><p>獎勵可能提高繳交意願，但「作業表現」適合決定「座位選擇權」嗎？${msg}</p>`,skillCards(),'fb-hit');attack(p,['fair'],'r2-complete','💥 PURPOSE–METHOD BREAK！',65,'final_boss_round2_hits');return}
if(q==='r3'){let rule=`<div class="fb-rule"><b>📜 班級規則</b>生日當天的同學，可以免除當天所有班級工作。</div><p>今天剛好有三個人生日：垃圾沒有倒、黑板沒有擦、午餐相關班務沒人處理。</p>`;if(p.final_boss_impacts?.r3){draw(p,'ROUND 3｜🎂 生日特權','福利規則出現',`${rule}<div class="fb-message">你先前選擇：<b>${p.final_boss_round3_answer||'已記錄的制度調整'}</b><br>本回合的 CLASS STATUS 已更新，不會再次套用。</div>`,`<div class="final-boss-next-action"><button class="primary" id="fb-r3-resume">繼續查看選擇影響</button></div>`);E('fb-r3-resume').onclick=()=>go(p,{final_boss_phase:'r3-impact',last_impact:p.last_impact||{}},false);return}draw(p,'ROUND 3｜🎂 生日特權','福利規則出現',`${rule}<h2>你會怎麼修改這條規則？</h2>`, `<div class="options">${['取消生日福利。','生日同學可免除部分工作，但原本工作必須事先安排代理。','生日同學完全不用做，其他人自己想辦法。','所有人生日當天仍必須完成全部工作。'].map((x,i)=>`<button class="choice fb-r3" data-i="${i}"><b>${'ABCD'[i]}.</b>${x}</button>`).join('')}</div>`);let ds=[{order:2,empathy:-2},{community:3,empathy:2},{freedom:2,community:-3},{order:2,empathy:-1}],ans=['取消生日福利','安排代理','其他人自己處理','完全不調整'];document.querySelectorAll('.fb-r3').forEach(b=>b.onclick=()=>apply(p,'r3',ans[+b.dataset.i],ds[+b.dataset.i],'r3-impact',{final_boss_round3_answer:ans[+b.dataset.i],final_boss_hp:50,final_boss_combo:ans[+b.dataset.i]==='安排代理'?combo(p)+1:combo(p)}));return}
if(q==='r3-impact')return impact(p,'r4','安排代理的方案同時用到：🔧 可執行性 ＋ 🤝 共同體責任。','⚔️ 進入下一回合');
if(q==='r4'){let done=(p.final_boss_round4a_hits||[]).includes('exec'),body=`<div class="fb-rule">準時到校 +2　作業準時 +3　回答問題 +1　主動撿起地上的垃圾並丟入垃圾桶 +2<br>忘帶課本 −2　上課講話 −3　午休講話 −2　垃圾分類錯誤 −1</div><p>35人 × 5天 × 4週 × 各種行為……計算、記錄、確認、爭議、重新計算。<br>班長：「老師……我不想當班長了。」</p>`;if(done){draw(p,'ROUND 4｜💻 超級班級積分制度','每件事情都有分數？',`${body}<div class="fb-message">你先前已使用：<b>🔧 可執行性</b><br>這套制度的記錄與確認成本太高，先檢查 Boss 的修補方案。</div>`,`<div class="final-boss-next-action"><button class="primary" id="fb-r4-resume">繼續檢查這套制度</button></div>`);E('fb-r4-resume').onclick=()=>go(p,{final_boss_phase:'r4-patch',last_impact:{}},false);return}draw(p,'ROUND 4｜💻 超級班級積分制度','每件事情都有分數？',body,skillCards());attack(p,['exec'],'r4-patch','💥 CRITICAL HIT！',50,'final_boss_round4a_hits');return}
if(q==='r4-complete'||(q==='r4-patch'&&(p.final_boss_round4b_hits||[]).includes('fair')))return roundComplete({...p,final_boss_hp:25},'💥 雙重技能破解！','ROUND 4｜超級班級積分制度',`<p class="fb-message">你發現：規則不只要做得到，也要思考不同加扣分是否合理。</p><p><b>BOSS HP　50% → 25%</b></p>`,'final-cases','⚔️ 進入最終回合');
if(q==='r4-patch'){draw(p,'⚠️ BOSS PATCH DETECTED','「那我找十個幹部一起記錄！」',`<p>人手不足的問題似乎解決了。</p><p>Boss 也把計分標準寫得很清楚：</p><div class="fb-rule">「午休期間開口交談一次 −2 分」<br>「主動撿起地上的垃圾並丟入垃圾桶 +2 分」</div><p>現在規則既有人執行，標準也很明確。<br>但把不同的班級行為都換成固定分數來管理，<br>這樣的制度本身合理嗎？${msg}</p>`,skillCards());attack(p,['fair'],'r4-complete','💥 DOUBLE SKILL BREAK！',25,'final_boss_round4b_hits');return}
if(q==='final-cases'){let cases=[['CASE 1｜🗳️ 34：1','冷氣固定 18°C。','一位同學：「可是我真的很怕冷……」'],['CASE 2｜🗳️ 32：3','午休全部關燈。','同學：「可是我今天需要處理事情……」'],['CASE 3｜🗳️ 32：3','班上表決通過：<br>「班級活動費全部拿來訂畢業紀念外套。」','同學：<br>「我不會買外套，為什麼我的班費也一定要拿來付？」','可是這也是多數決啊！']],i=p.final_boss_case_index||0,x=cases[i],last=i===2;draw(p,'FINAL ROUND｜所有事情一律多數決','「每個人一票，完全公平。」',`<div class="fb-cases"><b>${x[0]}</b><br>${x[1]}<br>${x[2]}</div><p>規則漏洞王：「${x[3]||'可是全部都是多數決啊！'}」</p>`,`<button class="secondary" id="fb-next-case">${last?'面對最終決策':'下一頁'}</button>`);E('fb-next-case').onclick=()=>go(p,{final_boss_phase:last?'final-decision':'final-cases',final_boss_case_index:last?0:i+1});return}
if(q==='final-decision'){let frags=[['👥 個別需求','👥 個別需求'],['👀 實際影響','👀 造成什麼後果'],['🎯 規則目的','🎯 規則目的'],['🧩 合理例外','🧩 合理例外'],['🗳️ 多數支持','🗳️ 多數支持'],['📜 人人相同','📜 人人相同'],['🔧 執行成本','🔧 執行成本']],coreValues=['👥 個別需求','🧩 合理例外'],analyzed=p.final_boss_final_fragments||[],core=p.final_boss_final_core_hits||analyzed.filter(x=>coreValues.includes(x)),order=p.final_boss_fragment_order;if(!order)return go(p,{final_boss_fragment_order:frags.map(x=>x[0]).sort(()=>Math.random()-.5)},false);let map=Object.fromEntries(frags),last=p.final_boss_final_last,feedback={
'👥 個別需求':'💥 核心命中！<br>相同規則可能忽略不同人的實際情況。代表學校外出比賽的同學無法在中午回到教室，和當時人在教室的同學，情況並不完全相同。<br>👾「等等……大家不是都要中午到場嗎？」',
'🧩 合理例外':'💥 核心命中！<br>共同規則仍可能需要合理例外。抽籤方式可以維持，但代表學校外出比賽的同學，可以事先登記或由他人代抽，不必因此失去資格。<br>👾「可惡……原來『所有人一樣』不一定就是公平！」',
'👀 實際影響':'🧩 這個角度有道理。規則實施後造成什麼結果，確實值得觀察；但這個情境已經告訴你，代表學校外出比賽的同學會失去抽籤資格。再往前想一步：為什麼「中午必須在教室」會造成這個問題？',
'🎯 規則目的':'🧩 這個角度有道理。抽籤的目的是選出校外教學人選；但這次最直接的問題是，要求本人中午在教室，與公平選出人選是否有必要關聯？',
'🗳️ 多數支持':'⚠️ 這正是 Boss 最想讓你相信的事情！多數決可以幫助班級形成共同決定，但「很多人支持」不等於「規則本身一定合理」。請再找真正的漏洞。',
'📜 人人相同':'⚠️ 小心！「每個人使用同一套規則」看起來很公平；但如果每個人的實際情況不同，完全相同的處理反而可能產生問題。再找找和「需求」或「例外」有關的碎片。',
'🔧 執行成本':'🧩 執行成本也是設計規則時的重要問題；但「抽籤選出校外教學人選」本身其實不難執行。這次真正的漏洞不是「做不做得到」，而是「中午必須在教室才能抽籤」是否合理。'};
let complete=core.length===2||!!p.final_boss_impacts?.['final-decision'],rule=`<div class="fb-rule"><b>📜 FINAL RULE</b>「班級所有事情，只要超過半數同學支持，就直接成為班級規定，所有人一律遵守。」</div><p>班上臨時獲得兩個可以公假參加校外教學的名額。老師早上公布消息後，班上決定用抽籤的方式選出兩名同學。為了方便處理，大家訂下規則：「只有今天中午人在教室的同學，才能參加抽籤。」</p><p>但是班上有一位同學當天正好代表學校外出比賽，中午無法回到教室。雖然他也想參加這次校外教學，卻因為中午不在教室而失去抽籤資格。</p><div class="fb-message warn">有人認為：「規則對每個人都一樣，中午不在教室就不能抽，這樣才公平。」<br>👾 規則漏洞王：「超過半數同意！而且每個人都用同一套規則！這樣總夠公平了吧？」</div>`;
let found=core.map(v=>map[v]).join('　＋　'),status=complete?`<div class="fb-double-break">💥 DOUBLE BREAK！<br><b>💥 雙重漏洞破解！</b><br>${found}<p>一項規則即使經過多數決，而且表面上每個人都適用相同標準，仍然要問：不同的人是否存在合理的不同需求？共同規則是否需要設計合理例外？</p></div>`:`<div class="fb-core-status">🔍 核心漏洞：<b>${core.length} / 2</b><br>已找到：${core.length?found:'？？？'}${core.length===1?'　＋　？？？':''}</div>`;
draw(p,'🧩 漏洞碎片分析','🔍 找出這條規則最核心的兩個漏洞',`${rule}<p class="fb-action-guide fb-final-guide">從已找到的漏洞中，選出最能直接指出問題核心的 2 個技能。</p><p>從 7 個漏洞碎片中，找出最能直接指出這次問題核心的 2 個。<br><b>你只有 2 次核心攻擊機會。</b></p>${status}${last?`<div class="fb-fragment-feedback ${coreValues.includes(last)?'core':''}">${feedback[last]}</div>`:''}<div class="fb-fragments">${order.map(value=>`<button class="fb-fragment ${analyzed.includes(value)?'analyzed':''} ${core.includes(value)?'core':''}" data-v="${value}" ${complete||analyzed.includes(value)?'disabled':''}>${map[value]}${core.includes(value)?'<small>⚔️ 核心命中</small>':analyzed.includes(value)?'<small>✓ 已分析</small>':''}</button>`).join('')}</div>`,`<div class="final-boss-next-action"><button class="primary" id="fb-final-attack" ${complete?'':'disabled'}>⚔️ 發動最終攻擊</button></div>`,complete?'fb-hit fb-double-hit':core.length?'fb-hit fb-final-core-hit':'');document.querySelectorAll('.fb-fragment').forEach(b=>b.onclick=()=>{let v=b.dataset.v;if(analyzed.includes(v)||complete)return;let nextAnalyzed=[...analyzed,v],nextCore=coreValues.includes(v)?[...core,v]:core;go(p,{final_boss_final_fragments:nextAnalyzed,final_boss_final_core_hits:nextCore,final_boss_final_last:v,final_boss_message:''},false)});E('fb-final-attack').onclick=()=>{if(!complete)return; if(p.final_boss_impacts?.['final-decision'])return go(p,{final_boss_phase:'final-attack',last_impact:{}},false);apply(p,'final-decision',core,{learning:2,order:2,empathy:2,community:3},'fusion',{final_boss_hp:25})};return}
if(q==='fusion')return impact(p,'final-attack','五項技能重新集合：📏 明確性　⚖️ 規範合理性　🧩 合理例外　🔧 可執行性　🤝 共同體責任。','⚔️ 發動最終攻擊');
if(q==='final-attack'){draw(p,'⚡ FINAL SKILL','🏛️ 規範設計力',`<p>好的規範需要：大家看得懂、目的與影響合理、能處理特殊情況、實際做得到，也有人願意共同維護。</p><div class="fb-final-beam"></div>`,`<button class="primary" id="fb-strike">⚔️ 發動最終攻擊</button>`,'fb-hit');E('fb-strike').onclick=()=>go(p,{final_boss_phase:'final-strike',final_boss_strike_step:0},false);return}
if(q==='final-strike'){let values=[16,8,3,0],i=p.final_boss_strike_step||0,v=values[i];draw({...p,final_boss_hp:v},'💥 CRITICAL HIT','RULE DESIGN BREAK！',`<p>五道技能光束命中規則漏洞王！</p><div class="fb-final-beam"></div>`,'','fb-hit');timer=setTimeout(()=>i>=values.length-1?go(p,{final_boss_phase:'defeated',final_boss_hp:0},false):go(p,{final_boss_phase:'final-strike',final_boss_strike_step:i+1,final_boss_hp:values[i+1]},false),620);return}
if(q==='defeated'){draw({...p,final_boss_hp:0},'🏆 FINAL BOSS DEFEATED','🏆 規則漏洞王已擊敗！',`<div class="fb-victory-flash"><b>🎉 恭喜過關！</b><p>RULE BUG KING HP 0%</p></div><p>規則漏洞王逐漸消散，飛舞的規則紙停了下來，教室恢復平靜。</p><p>《無規則教室》的所有關卡已完成。</p>`,`<button class="primary" id="fb-victory">查看全破成果</button>`,'fb-defeated');E('fb-victory').onclick=()=>go(p,{final_boss_phase:'victory',final_boss_hp:0},false);return}
if(q==='victory'){draw({...p,final_boss_hp:0},'🏆 FINAL BOSS DEFEATED','🎉 恭喜全破！',`${avatarHero(p)}<p>你一路破解了不同的規則漏洞。</p><div class="fb-skill-cards fb-earned-skills">${SK.slice(1).concat(SK.slice(0,1)).map(([,icon,name])=>`<div class="fb-skill">${icon} ${name}</div>`).join('')}</div><div class="fb-achievement">🔍 規範判讀力</div><p>你不一定是制定規則的人，但你已經學會從不同角度理解與判斷規則。</p>`,`<button class="primary" id="fb-analyze">✨ 揭曉我的最終角色</button>`,'fb-victory');E('fb-analyze').onclick=()=>go(p,{final_boss_phase:'ending-analysis'},false);return}
if(q==='ending-analysis'){draw({...p,final_boss_hp:0},'🧬 ENDING ANALYSIS','最終角色分析',`<p>正在整理你一路做過的選擇……</p><div class="fb-analysis-icons"><i>🕊️</i><i>📚</i><i>⚖️</i><i>❤️</i><i>🤝</i><i>🔧</i></div><p class="fb-message">分析完成後，將揭曉你最容易先注意到的規範角度。</p>`,'','fb-analysis');timer=setTimeout(async()=>{let e=await persistEnding(p);await go(p,{final_boss_phase:'ending-card',final_boss_cleared:true,ending_type:e.type,ending_top3:e.top.map(x=>x.key),final_profile_scores:e.scores},false)},2400);return}
if(q==='ending-card'){let e=endingMeta(p);draw({...p,final_boss_hp:0},'🧬 YOUR FINAL ROLE','你的班級生存角色是——',`${avatarHero(p)}<h2 class="fb-role-title">${e.title}</h2><p>${e.description}</p><p class="fb-reminder"><b>提醒：</b>${e.reminder}</p>${radar(e)}`,`<button class="primary" id="fb-all-clear">🏆 查看最終結尾</button>`,'fb-ending');E('fb-all-clear').onclick=()=>go(p,{final_boss_phase:'all-clear',final_boss_cleared:true},false);return}
if(q==='clear')return go(p,{final_boss_phase:'ending-analysis',final_boss_hp:0},false);
if(q==='all-clear'){draw({...p,final_boss_hp:0},'🏆 ALL CLEAR','全部關卡完成',`<p>《無規則教室：班級生存挑戰》</p><p>你已完成所有挑戰。</p><div class="fb-message"><b>規則不是為了消滅自由。</b><br>而是讓一群不同的人，能夠一起生活。</div>`,`<div class="fb-ending-actions"><button class="secondary" id="fb-role-card">🧬 查看我的角色卡</button><button class="primary" id="fb-return">🏫 返回教室</button></div>`,'fb-ending');E('fb-role-card').onclick=()=>go(p,{final_boss_phase:'ending-card',final_boss_cleared:true},false);E('fb-return').onclick=async()=>{clearTimer();await window.NRC_RETURN_TO_HUB({flow:'hub',final_boss_cleared:true,final_boss_phase:'done',last_impact:{}})};return}
draw({...p,final_boss_hp:0},'🏆 ALL CLEAR','全部關卡完成',`<p>你已完成所有挑戰。</p>`,`<button class="primary" id="fb-return">🏫 返回教室</button>`,'fb-ending');E('fb-return').onclick=async()=>window.NRC_RETURN_TO_HUB({flow:'hub',final_boss_cleared:true,final_boss_phase:'done',last_impact:{}});
};
document.addEventListener('click',async e=>{let b=e.target.closest?.('#final-boss-zone');if(!b)return;let id=ID();if(!id)return;let p=await GameAPI.call('getStudent',id);if(!p?.level4_cleared)return;e.preventDefault();e.stopImmediatePropagation();if(p.final_boss_cleared)return window.NRC_SHOW_COMPLETED_LEVEL?.('finalboss');let phase=p.final_boss_phase&&p.final_boss_phase!=='done'?p.final_boss_phase:'intro';await GameAPI.call('student',{class:id.class,seat:id.seat,data:{flow:'finalboss',final_boss_phase:phase,last_impact:{}}});window.NRC_FINAL_BOSS()},true);
document.addEventListener('click',async e=>{let b=e.target.closest?.('#test-back');if(!b||!document.querySelector('.final-boss-scene'))return;e.preventDefault();e.stopImmediatePropagation();let p=await GameAPI.call('getStudent',ID());if(!p||p.flow!=='finalboss'||p.final_boss_phase==='done'||p.final_boss_phase==='defeated')return;clearTimer();let h=JSON.parse(sessionStorage.getItem(KEY)||'[]'),x=h.pop();if(!x)return alert('目前沒有更早的 FINAL BOSS 畫面。');sessionStorage.setItem(KEY,JSON.stringify(h));let shown=review?.view||{phase:p.final_boss_phase,dialogue:p.final_boss_dialogue_index||0,caseIndex:p.final_boss_case_index||0},future=review?.future||[];future.push(shown);review={official:p,view:x,future};window.NRC_FINAL_BOSS()},true);
const oldSync=window.NRC_SYNC_HUB;window.NRC_SYNC_HUB=async()=>{let p=await oldSync?.(),side=document.querySelector('#final-boss-zone');document.querySelector('#council-zone')?.remove();if(!p||!side)return p;if(p.final_boss_cleared){side.className='hotspot side cleared';side.disabled=false;side.removeAttribute('aria-disabled');side.innerHTML='<b>👾 規則漏洞大決戰</b><span>🏆 CLEARED｜FINAL BOSS</span>'}else if(p.level4_cleared){side.className='hotspot side new';side.disabled=false;side.removeAttribute('aria-disabled');side.innerHTML='<b>👾 規則漏洞大決戰</b><span>✨ NEW｜FINAL BOSS</span>'}return p};
setTimeout(()=>window.NRC_SYNC_HUB?.(),0);
})();

