/* LEVEL 4｜獨立探索模組：不改動既有 LEVEL 1～3 與 Hub。 */
(()=>{const H='nrc-l4-history';let timer;const N={freedom:'🕊️ 自由度',learning:'📚 學習效率',order:'⚖️ 班級秩序',empathy:'❤️ 同學感受',community:'🤝 共同責任'},I=()=>JSON.parse(localStorage.getItem('nrc-id')||'null'),S=p=>({freedom:50,learning:50,order:50,empathy:50,community:50,...(p.class_state||{})}),P=p=>`${((p.avatar_index||0)%4)*33.333}% ${(p.avatar_index||0)>3?'100%':'0%'}`,T=()=>{clearInterval(timer);timer=null},E=x=>document.getElementById(x),HIST=p=>{let h=JSON.parse(sessionStorage.getItem(H)||'[]');h.push({level4_phase:p.level4_phase||'intro'});sessionStorage.setItem(H,JSON.stringify(h))},HUD=p=>{let s=S(p),d=p.last_impact||{};return `<aside class="rpg-hud"><div class="hud-player"><i class="avatar-sprite hud-avatar" style="background-position:${P(p)}"></i><span><b>${p.avatar_id}</b><br>🎒 班級新成員</span></div><b>🏫 CLASS STATUS</b>${Object.entries(N).map(([k,n])=>`<div class="meter"><span>${n}</span><strong>${s[k]}</strong><i style="width:${s[k]}%"></i>${d[k]?`<em>${d[k]>0?'▲':'▼'}${Math.abs(d[k])}</em>`:''}</div>`).join('')}</aside>`},opt=a=>`<div class="options l4-options">${a.map((x,i)=>`<button class="choice l4-choice" data-i="${i}"><b>${'ABCD'[i]}.</b>${x}</button>`).join('')}</div>`,go=async(p,d,history=true)=>{T();if(history)HIST(p);await GameAPI.call('student',{class:p.class,seat:p.seat,data:{flow:'level4',...d}});NRC_LEVEL4()},apply=async(p,key,answer,delta,next,extra={})=>{if(p.level4_impacts_applied?.[key])return go(p,{level4_phase:next,last_impact:{}});let s=S(p);Object.entries(delta).forEach(([k,v])=>s[k]=Math.max(0,Math.min(100,s[k]+v)));await go(p,{...extra,class_state:s,last_impact:delta,level4_impacts_applied:{...(p.level4_impacts_applied||{}),[key]:true},level4_phase:next})},draw=(p,tag,title,body,actions='',asset='assets/level4-classroom-check.png',cls='')=>{T();E('stage-label').textContent='LEVEL 4｜教室裡的最後一個垃圾';E('app').innerHTML=`<div class="game-scene l4-game ${cls}"><img class="scene-img" src="${asset}">${HUD(p)}<i class="scene-avatar" style="background-position:${P(p)}"></i><section class="dialogue l4-panel"><p class="eyebrow">${tag}</p><h1>${title}</h1>${body}${actions}</section></div>`},impact=(p,next,text)=>{let s=S(p),d=p.last_impact||{};draw(p,'你的選擇讓班級產生了影響。','CLASS STATUS',`<div class="impact-result l4-impact">${Object.entries(d).map(([k,v])=>`<span>${N[k]} <b>${s[k]-v} → ${s[k]}</b> <strong class="${v>0?'up':'down'}">${v>0?'+':''}${v}</strong></span>`).join('')}</div><p>${text}</p>`,`<button class="primary" id="l4-next">繼續看下去</button>`);E('l4-next').onclick=()=>go(p,{level4_phase:next,last_impact:{}})};
 const avatarIndex=name=>Math.max(0,GAME.avatars.indexOf(name)),classmateLine=(name,line)=>{let i=avatarIndex(name);return `<span class="l4-classmate-line"><span class="l4-classmate-avatar"><i class="avatar-sprite" style="background-position:${P({avatar_index:i})}"></i></span><span><b>${name}</b>：${line}</span></span>`};
 document.addEventListener('click',async e=>{let b=e.target.closest&&e.target.closest('#test-back');if(!b)return;let p=await GameAPI.call('getStudent',I());if(!p||p.flow!=='level4')return;e.preventDefault();e.stopImmediatePropagation();T();let h=JSON.parse(sessionStorage.getItem(H)||'[]'),x=h.pop();if(!x)return alert('目前沒有更早的 LEVEL 4 畫面。');sessionStorage.setItem(H,JSON.stringify(h));await GameAPI.call('student',{class:p.class,seat:p.seat,data:{flow:'level4',...x,last_impact:{}}});NRC_LEVEL4()},true);
window.NRC_LEVEL4=async()=>{let p=await GameAPI.call('getStudent',I());if(!p)return;let q=p.level4_phase||'intro',found=p.classroom_check_found||[],check=()=>go(p,{level4_phase:'check',last_impact:{}}),done=found.length===4&&p.paper_cup_action&&p.recycle_action&&p.unassigned_task_answer&&p.responsibility_question;
if(q==='intro'){draw(p,'LEVEL 4｜♻️ 教室裡的最後一個垃圾','放學後的教室',`<p>🔔 放學鐘響。</p><div class="l4-classmate-lines">${classmateLine('小晴','「今天的打掃終於完成了！」')}${classmateLine('阿樂','「我的工作也做完了。」')}${classmateLine('小米','「可以回家了吧？」')}</div><p class="l4-mission">MISSION COMPLETE？</p>`,'<button class="primary" id="l4-start">離開教室</button>','assets/level4-classroom-check.png','l4-intro-layout');E('l4-start').onclick=()=>go(p,{level4_phase:'warning'});return}
if(q==='warning'){draw(p,'⚠️ WAIT...','你的工作完成了。','<p>但是……教室真的整理完成了嗎？</p><div class="l4-system">🔍 CLASSROOM CHECK<br><small>找出教室裡還沒處理的事情。</small></div>','<button class="primary" id="l4-check-start">開始檢查</button>','','l4-warning');E('l4-check-start').onclick=check;return}
if(q==='check'){let a=['cup','recycle','window','power'],map={cup:'cup-event',recycle:'recycle-event',window:'unassigned-event',power:'unassigned-event'},discover={cup:['🥤','地上還有飲料紙杯。'],recycle:['♻️','回收分類似乎有錯誤。'],window:['🪟','窗戶還沒有關好。'],power:['💡','教室裡還有沒有關閉的電燈／電扇。']};draw(p,'🔍 CLASSROOM CHECK','放學後的教室探索',`<p class="l4-found-count">已發現：<b>${found.length} / 4</b></p>${done?'<p class="l4-system">✓ CLASSROOM CHECK COMPLETE<br><small>已找出教室裡所有需要處理的事情。</small></p>':'<p class="l4-explore-tip">移動滑鼠探索教室，找出還沒處理好的地方。</p>'}<div class="l4-hotspots">${a.map(k=>`<button class="l4-hotspot ${found.includes(k)?'found':''}" data-k="${k}" aria-label="${found.includes(k)?'已發現，可重新查看':'調查可疑區域'}"><span>${found.includes(k)?'✓ 已發現':'🔍 調查'}</span></button>`).join('')}</div>`,done?'<button class="primary" id="l4-final">面對責任史萊姆</button>':'','assets/level4-classroom-explore.png','l4-check-mode');let game=document.querySelector('.l4-game');game.append(document.querySelector('.l4-hotspots'));document.querySelectorAll('.l4-hotspot').forEach(b=>b.onclick=()=>{let k=b.dataset.k,seen=found.includes(k),d=discover[k];document.querySelector('.l4-discovery-card')?.remove();let card=document.createElement('aside');card.className='l4-discovery-card';card.setAttribute('aria-live','polite');card.innerHTML=`<p class="l4-discovery-title">${d[0]} 發現問題！</p><p>${d[1]}</p><button class="primary l4-discovery-action">${seen?'繼續探索':'查看並處理'}</button>`;game.append(card);card.querySelector('.l4-discovery-action').onclick=()=>seen?card.remove():go(p,{classroom_check_found:[...new Set([...found,k])],level4_current_event:k,level4_phase:map[k]})});if(done)E('l4-final').onclick=()=>go(p,{level4_phase:'final-boss'});return}
if(q==='cup-event'){draw(p,'EVENT 1｜🥤 又不是我丟的','喝完的飲料紙杯掉在地上。','<div class="l4-cup">🥤</div><p>系統：「不是你丟的。」<br>「而且你的打掃工作已經完成了。」</p>','<button class="primary" id="l4-cup-next">我會怎麼做？</button>');E('l4-cup-next').onclick=()=>go(p,{level4_phase:'cup-question'});return}
if(q==='cup-question'){let a=['不是我的，不處理。','告訴今天負責掃地的同學。','順手撿起來，依班級垃圾分類方式處理。','找出是誰丟的，請他自己處理。'],d=[{freedom:2,community:-4},{order:2,community:1},{community:4,empathy:1},{order:3,empathy:-1}];if(p.paper_cup_action){draw(p,'EVENT 1｜已記錄','你已經做出決定。','<p>完成個人分工，不一定等於共同環境也已完成。</p>','<button class="primary" id="l4-record">繼續</button>');E('l4-record').onclick=()=>go(p,{level4_phase:'slime'});return}draw(p,'QUESTION','你會怎麼做？','',opt(a));document.querySelectorAll('.l4-choice').forEach(b=>b.onclick=()=>{let i=+b.dataset.i;apply(p,'cup',a[i],d[i],'cup-impact',{paper_cup_action:a[i],community_trash:a[i]})});return}
if(q==='cup-impact')return impact(p,'slime','共同環境的問題，常落在「不是我分內」的縫隙裡。');
if(q==='slime'){draw(p,'⚠️ WARNING','RESPONSIBILITY SLIME APPEARS','<img class="l4-slime" src="assets/responsibility-slime.png"><p>👾「不是你的，幹嘛管？」<br>「大家只要做好自己的工作就好了啊！」<br>「反正……應該會有人處理吧？」</p><div class="l4-hp">👾 HP<i></i></div>','<button class="primary" id="l4-talk">聽聽同學怎麼說</button>','','l4-warning');E('l4-talk').onclick=()=>go(p,{level4_phase:'talk'});return}
if(q==='talk'){let a=[['阿樂','不是我丟的啊。'],['小晴','我今天負責黑板。'],['阿哲','我的工作已經做完了。'],['小米','應該會有人處理吧？']],n=0;draw(p,'EVENT 2｜每個人都做好自己的事','同學們的回答','<div class="l4-speech"><span class="l4-classmate-avatar"><i class="avatar-sprite l4-speaker"></i></span><div><b id="l4-name"></b><p id="l4-line"></p></div></div><p>🥤 飲料紙杯仍然在地上。👾 HP / SIZE ↑</p>','<button class="secondary" id="l4-skip">跳過對話</button>');let show=()=>{let x=a[n];E('l4-name').textContent=x[0];E('l4-line').textContent='「'+x[1]+'」';document.querySelector('.l4-speaker').style.backgroundPosition=P({avatar_index:avatarIndex(x[0])});n++};show();timer=setInterval(()=>n>=a.length?(T(),go(p,{level4_phase:'responsibility-question'})):show(),2400);E('l4-skip').onclick=()=>{T();go(p,{level4_phase:'responsibility-question'})};return}
if(q==='responsibility-question'){let a=['是，大家做好自己的事情就夠了。','不一定，有些事情沒有明確分配給誰。','不一定，共同環境有時需要有人主動處理。','這應該是幹部的責任。'];if(p.responsibility_question){check();return}draw(p,'QUESTION','如果每個人都完成自己的分工，班級就一定會維持得很好嗎？','',opt(a));document.querySelectorAll('.l4-choice').forEach(b=>b.onclick=()=>{let i=+b.dataset.i,hit=i===1||i===2;go(p,{responsibility_question:a[i],responsibility_hit:hit,level4_phase:'responsibility-result'})});return}
if(q==='responsibility-result'){draw(p,p.responsibility_hit?'💥 RESPONSIBILITY HIT！':'⚠️ 真的嗎？',p.responsibility_hit?'責任史萊姆縮小了一點。':'責任史萊姆：「沒錯沒錯！」',`<p>${p.responsibility_hit?'有些共同需要並沒有被分配給誰。':'共同環境裡的事情，真的總是有人被分配處理嗎？'}</p>`,'<button class="primary" id="l4-backcheck">返回探索</button>');E('l4-backcheck').onclick=check;return}
if(q==='recycle-event'){draw(p,'EVENT 3｜♻️ 回收放錯了','CLASSIFICATION ERROR','<p>你看到同學把一個已清空、依班級目前垃圾分類規定應放入回收區的<b>飲料紙杯</b>，丟進一般垃圾。</p>','<div class="l4-actions"><button class="primary" data-a="speak">💬 開口提醒</button><button class="primary" data-a="self">🤐 不說話，自己處理</button><button class="primary" data-a="ignore">🚶 當作沒看到</button></div>','assets/level4-recycle-error.png');document.querySelectorAll('.l4-actions button').forEach(b=>b.onclick=()=>go(p,{recycle_action:b.dataset.a,level4_phase:b.dataset.a==='speak'?'reminder':'recycle-result'}));return}
if(q==='reminder'){let a=['😠「你連回收都不會喔？」','🙂「欸，這個好像要丟回收喔。」','😐「你丟錯了，拿回去重丟。」'],d=[{empathy:-3,order:1},{empathy:2,community:2},{order:2}];draw(p,'💬 DIALOGUE ACTION','選擇你的提醒方式','',opt(a),'assets/level4-recycle-error.png');document.querySelectorAll('.l4-choice').forEach(b=>b.onclick=()=>{let i=+b.dataset.i;apply(p,'recycle',a[i],d[i],'recycle-impact',{reminder_style:a[i],community_reminder_style:a[i],recycle_action:'speak'})});return}
if(q==='recycle-result'){let self=p.recycle_action==='self';apply(p,'recycle',self?'不說話，自己處理':'當作沒看到',self?{community:1}:{community:-2},'recycle-impact',{reminder_style:self?'不說話，自己處理':'當作沒看到'});return}
if(q==='recycle-impact')return impact(p,'check',p.recycle_action==='speak'?(p.reminder_style.includes('欸')?classmateLine('小米','😮「喔對耶，我丟錯了，謝啦。」'):p.reminder_style.includes('連回收')?classmateLine('阿凱','😑「知道啦……幹嘛這麼兇。」'):classmateLine('阿樂','😶「喔……好。」')):'問題已處理；但提醒與否也會影響共同維護。');
if(q==='unassigned-event'){let x=p.level4_current_event==='window'?'🪟 窗戶沒有關好':'💡／🌀 電燈、電扇仍然開著';draw(p,'EVENT 4｜沒有人負責的事情',x,'<p>系統：「今天的打掃分工表上……好像沒有寫誰負責這件事。」</p><p>👾「沒有人被分配到＝沒有人要做！」</p>','<button class="primary" id="l4-un">想一想</button>');E('l4-un').onclick=()=>go(p,{level4_phase:'unassigned-question'});return}
if(q==='unassigned-question'){let a=['沒有人被分配，就不用處理。','等幹部發現。','看見的人可以先處理，或提醒大家一起處理。','重新把所有可能發生的事情全部寫進打掃分工表。'],d=[{community:-3},{order:1,community:-1},{community:4,empathy:1},{order:2}];if(p.unassigned_task_answer){check();return}draw(p,'QUESTION','如果共同環境出現一件「沒有明確分配給任何人」的事情，比較適合怎麼處理？','',opt(a));document.querySelectorAll('.l4-choice').forEach(b=>b.onclick=()=>{let i=+b.dataset.i;apply(p,'unassigned',a[i],d[i],'unassigned-impact',{unassigned_task_answer:a[i]})});return}
if(q==='unassigned-impact')return impact(p,'check',String(p.unassigned_task_answer).startsWith('重新')?'🔧 所有情況真的都能事先寫完嗎？':'共同環境有些需要，正好沒有被分工表預先寫到。');
if(q==='final-boss'){draw(p,'👾 FINAL BOSS','責任史萊姆最終戰','<img class="l4-slime l4-big" src="assets/responsibility-slime.png"><p>「不可能！明明每個人都完成自己的工作了！」</p><div class="l4-system">35 PEOPLE ✓ 每個人完成自己的分工<br>🥤垃圾　♻️分類錯誤　🪟窗戶　🌀電扇</div>','<button class="primary" id="l4-fq">最後回答</button>','','l4-warning');E('l4-fq').onclick=()=>go(p,{level4_phase:'final-question'});return}
if(q==='final-question'){let a=['一定可以。','不一定，共同生活還需要有人願意看見並回應沒有被分配的共同需要。'];draw(p,'QUESTION','如果每個人都只處理「被分配給自己的事情」，共同環境就一定能維持好嗎？','',opt(a));document.querySelectorAll('.l4-choice').forEach(b=>b.onclick=()=>{let i=+b.dataset.i;apply(p,'final',a[i],i?{community:3,empathy:1}:{},'final-result',{responsibility_final_answer:a[i],community_boss_answer:a[i]})});return}
if(q==='final-result'){let hit=String(p.responsibility_final_answer).startsWith('不一定');draw(p,hit?'💥 FINAL HIT！':'⚠️ 再看一次教室。',hit?'RESPONSIBILITY SLIME DEFEATED':'剛才教室裡發生的事情呢？',`<img class="l4-slime" src="${hit?'assets/responsibility-slime-defeated.png':'assets/responsibility-slime.png'}"><div class="l4-hp"><i style="width:${hit?'0':'18'}%"></i></div><p>${hit?'共同需要被看見並回應。':'🥤、♻️、🪟、🌀 都可能沒有人被指定處理。'}</p>`,'<button class="primary" id="l4-skill">解鎖技能</button>');E('l4-skill').onclick=()=>go(p,{level4_phase:'skill'});return}
if(q==='skill'){let unlocked=[...new Set([...(p.unlocked||[]),'🤝 共同體責任'])];draw(p,'🔓 SKILL UNLOCKED','🤝 共同體責任','<div class="l4-system">做好自己的事情，是「個人責任」。<br>👀 看見共同需要 ↓ 🙋 願意處理 ↓ 💬 適當提醒 ↓ 🤝 一起維護<br><br>共同責任不是什麼事情都要你負責，而是在共同生活中，願意多看一步。</div>','<button class="primary" id="l4-clear">查看通關結果</button>');E('l4-clear').onclick=()=>go(p,{unlocked,level4_phase:'clear'});return}
draw(p,'🗑️ STAGE CLEAR','教室裡的最後一個垃圾完成！','<p>本關取得：<b>🤝 共同體責任</b></p><p class="l4-mission">「我的工作完成」≠「共同環境一定完成」</p>','<button class="primary" id="l4-return">🏫 返回教室</button>');E('l4-return').onclick=async()=>{T();await NRC_RETURN_TO_HUB({flow:'hub',level4_cleared:true,level4_phase:'done',last_impact:{}})};
};
const level4Render=window.NRC_LEVEL4;
window.NRC_LEVEL4=async()=>{await level4Render();requestAnimationFrame(()=>{let box=s=>{let e=document.querySelector(s);if(!e)return null;let r=e.getBoundingClientRect(),c=getComputedStyle(e);return {selector:s,left:r.left,top:r.top,width:r.width,height:r.height,position:c.position,display:c.display,transform:c.transform,overflow:c.overflow,zIndex:c.zIndex,pointerEvents:c.pointerEvents}};console.debug('[LEVEL4 UI DEBUG]',{viewport:{width:innerWidth,height:innerHeight},app:box('#app'),root:box('.l4-game'),panel:box('.l4-panel'),question:box('.l4-options'),button:box('.l4-panel button')})})};
})();
