const levels=[
 {zone:'第一章・手機迷霧',boss:'分心小怪',intro:'鐘聲已響，卻有人還在滑手機。黑霧吞掉了全班的注意力。你要怎麼開啟第一個班級規範？',choices:[['先訂出「課堂中手機收起來」的明確規則。','明確','規則清楚，大家知道何時該放下手機。'],['直接沒收所有人的手機。','壓制','短暫安靜，但規則的理由沒有被理解。'],['假裝沒看到，等大家自覺。','放任','黑霧變得更濃：沒有共同期待，秩序很難形成。']]},
 {zone:'第二章・午餐混戰',boss:'桌面史萊姆',intro:'午餐後的教室像剛結束一場怪獸派對：垃圾、氣味與抱怨四處蔓延。規範要怎樣才會被大家遵守？',choices:[['全班討論「誰、何時、怎麼做」，寫成可執行約定。','共識','約定具體又可行，獲得技能：合作指令。'],['只寫「請保持整潔」。','模糊','大家都同意，但每個人理解的「整潔」不同。'],['指定幾個人永遠負責收拾。','不公平','少數人負擔過重，反而產生新的不滿。']]},
 {zone:'第三章・最終教室',boss:'規則黑霧・BOSS',intro:'黑霧的真身出現了！它靠著「不清楚、不公平、沒人一起維護」吸收力量。現在，選擇你的班級戰術。',choices:[['規範要清楚：每個人知道該做什麼。','清楚','黑霧的「模糊」護盾破裂。'],['規範要公平：權利與責任要能被說明。','公平','黑霧的「偏心」護盾破裂。'],['規範要共同維護：有提醒，也有修正空間。','共維','黑霧的「冷漠」護盾破裂。']]}
];
let state={level:0,score:0,skill:0,hp:100};const game=document.querySelector('#game');
function shell(content){game.innerHTML=`<div class="game-shell">${content}</div>`}function start(){shell(`<section class="start"><div class="start-card"><p class="rune">SOCIAL NORMS × CLASS RPG</p><h1>無規則教室<br>班級生存挑戰</h1><p>規則消失後，教室被「規則黑霧」吞沒。你不是來填問卷的——你是班級的規範冒險者。</p><button id="start">進入教室</button><p class="tip">手機直向即可遊玩・每次選擇都會改變最終戰力</p></div></section>`);document.querySelector('#start').onclick=scene}
function ui(){let l=levels[state.level];return `<header class="hud"><span class="badge">${l.zone}</span><span class="phase">規範能量 ${state.score} / 3</span></header><section class="battlefield"><div class="nameplate"><b>${l.boss}</b><div class="bar"><i style="width:${state.hp}%"></i></div></div><div class="hero"></div><div class="boss"></div><div class="magic"></div></section>`}
function scene(){let l=levels[state.level];shell(`${ui()}<section class="dialogue"><span class="speaker">【遭遇事件】</span><p class="text">${l.intro}</p><div class="choices">${l.choices.map((c,i)=>`<button class="choice" data-i="${i}"><b>${'ABC'[i]}・${c[1]}</b>${c[0]}</button>`).join('')}</div><p class="tip">選擇後將轉化為戰鬥效果。</p></section>`);document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>result(+b.dataset.i))}
function result(i){let choice=levels[state.level].choices[i],good=i===0||(state.level===2&&i<3);if(good){state.score++;state.skill=Math.min(2,state.skill+1)}let damage=good?36:15;state.hp=Math.max(0,state.hp-damage);shell(`${ui()}<section class="dialogue"><span class="speaker">【結果】</span><p class="text">${choice[2]}</p><p class="unlocked">${good?'✦ 規範能量 +1　技能槽充能！':'✦ 黑霧只受到些微影響。'}</p><button class="next" id="fight">${state.level===2?'進入最終戰':'用規範反擊'}</button></section>`);document.querySelector('#fight').onclick=()=>fight(good)}
function fight(good){shell(`${ui()}<section class="dialogue"><span class="speaker">【戰鬥回合】</span><p class="text">選擇技能，讓班級從混亂中找回秩序。</p><div class="skills"><button class="skill" data-d="18"><b>1・明確說明</b>讓期待看得見</button><button class="skill" data-d="28"><b>2・共同討論</b>讓規則有理由</button><button class="skill" data-d="42" ${state.skill<2?'disabled':''}><b>3・班級共識</b>技能解鎖！</button></div></section>`);document.querySelectorAll('.skill').forEach(b=>b.onclick=()=>attack(+b.dataset.d))}
function attack(dmg){state.hp=Math.max(0,state.hp-dmg);let boss=document.querySelector('.boss'),hero=document.querySelector('.hero'),magic=document.querySelector('.magic');boss.classList.add('hit');hero.classList.add('hit');magic.classList.add('show');setTimeout(()=>{if(state.level===2)victory();else{state.level++;state.hp=100;scene()}},800)}
function victory(){shell(`${ui()}<section class="victory"><div><p class="rune">FINAL BOSS CLEARED</p><h2>CLASS VICTORY!</h2><p>你擊退的不是「不聽話的同學」，而是讓大家不知道如何一起生活的黑霧。有效的社會規範，需要清楚、公平，並由成員共同維護。</p><div class="rules"><span>清楚：行動、時間與情境要具體。</span><span>公平：規則能被合理說明，不只靠權力。</span><span>共維：彼此提醒，也願意因情境修正。</span></div><button class="next" id="again">重新挑戰</button></div></section>`);document.querySelector('#again').onclick=()=>{state={level:0,score:0,skill:0,hp:100};start()}}
start();
